server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://nobug-project-db.czx0h15iygdm.us-east-2.rds.amazonaws.com:3306/test_db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: admin
    password: nopassword
mybatis:
  mapper-locations: classpath:mapper/*.xml
